---
# defaults vars for fail2ban
bantime_d: 50
findtime_d: 30
maxretry_d: 1
ignoreip_d: 127.0.0.1
bantime_increment_d: true

enabled_sshd: true

enabled_recidive: true
bantime_recidive: -1
findtime_recidive: 86400
maxretry_recidive: 15

#defaults vars for install
ver_for_redos: 1.1.0-4.red80
